### ISSUE TITLE
What about Safari?

### ISSUE THREAD

**Issue by sookoll** [matt-kruse/old-layout#1]
Is there a possibility to get this working on Safari?

**Comment by matt-kruse** [comment]
I am working on updating my macos, safari, and xcode right now to give it a shot. I have very old mac hardware. We'll see if it works...

**Comment by sookoll** [comment]
I don't know what You did, but without installing anything on Safari side, my Facebook there looks also old. So thanks!

**Comment by sookoll** [comment]
From 6 it worked for acount, so also in Safari. Closed this one.
