### ISSUE TITLE
Does not work anymore since yesterday (2020-10-23)

### ISSUE THREAD

**Issue by terremoth** [matt-kruse/old-layout#17]
![image](https://user-images.githubusercontent.com/11032344/97003866-8468fe00-1512-11eb-9bbc-a4e0b5a176e8.png)

**Comment by Tyler-H** [comment]
Yep, they finally started serving the new layout to the upload.facebook.com domain on 10/22. Solutions at this point will likely require extensive JS layout changes. Bummer!

**Comment by wazroth** [comment]
Matt has a workaround for now: go to a group you admin and on the left you should see an option to switch back for 48 hours in order to use the old admin interface. But this sticks everywhere on the site.

If you don't admin any groups, start a new group and you'll be the admin.

**Comment by DoNotSpamPls** [comment]
@wazroth I just created a new group, but I don't seem to have that option - maybe they removed that as well :/

**Comment by wazroth** [comment]
@DoNotSpamPls hmm, the conversation on facebook seems to indicate mixed success with that method too. As an alternative some folks are saying they get the option if they're the admin for a page -- could try that too.

**Comment by dmitriy1980** [comment]
@DoNotSpamPls Just a thought. Make sure that in the past you did not hide it with Sfx's "Hide/Show Parts of the Page"

**Comment by DoNotSpamPls** [comment]
@wazroth that seems to work, thanks a lot!

**Comment by paolocesari** [comment]
Since 24 October 2020 Facebook can't load page with active add-on and the icon image of "Old Layout" disappeared from Firefox bar.
Only when deactivate "Old Layout" Facebook can load with the new terrible layout.
<img width="731" alt="facebook" src="https://user-images.githubusercontent.com/31792800/97085773-c59b0400-161f-11eb-8bc0-d6cfd3661858.png">

**Comment by frozenpandaman** [comment]
@wazroth thank you, this works (for now)!!
![image](https://user-images.githubusercontent.com/7245874/97386509-372db900-1891-11eb-9ea1-18de5cda28fa.png)

**Comment by terremoth** [comment]
it is now working

**Comment by frozenpandaman** [comment]
they seem to have removed the 'switch back for 48 hours' feature on the group admin page :(
