### ISSUE TITLE
Attempting to join a group video call gives a "Browser not supported" error

### ISSUE THREAD

**Issue by steveiaco** [matt-kruse/old-layout#2]
Attempting to join a group video call with the extension enabled and while using Google Chrome (Version 85.0.4183.121) gives a browser not supported error.

"Switch Browsers to Make Group Video Chats
Unfortunately, our group calling feature doesn't support your browser yet. To make a group video call, open in Google Chrome."

**Comment by matt-kruse** [comment]
Yes, this is a side-effect of Facebook thinking you are using an older browser.

**Comment by steveiaco** [comment]
Ahh I see, I was under the impression the extension was an overlay for the new interface. I guess you're just spoofing an older browser then?

**Comment by matt-kruse** [comment]
Yes, that's exactly what it does! :)

**Comment by steveiaco** [comment]
Great! Thanks :)
