### ISSUE TITLE
Notification issues?

### ISSUE THREAD

**Issue by grieves13** [matt-kruse/old-layout#22]
I am not sure if this is an actual issue with the plugin, or FB is just shit lately, but i started to notice, that if somebody mentions me in a comment, there is no notification about it as there was before... Might be an issue with the new FB, but potentially might be caused by the plugin. Any chance you could check it?

**Comment by NitroV** [comment]
> FB is just shit lately

Always has been.

> if somebody mentions me in a comment, there is no notification about it as there was before

Did you check if the mention notifications are present after disabling the extension? If you have a mobile device, make sure you're getting notifications for the mentions on your app. If that's not the case, have a look at [notification settings on facebook](https://www.facebook.com/settings?tab=notifications) to see whether the notifications are enabled for mentions.

Alternatively you can also bookmark the [direct link to all notifications](https://www.facebook.com/notifications), if the notification pop-up window is bugged somehow, you should find all your notifications there.

**Comment by grieves13** [comment]
> > FB is just shit lately
> 
> Always has been.
> 
> > if somebody mentions me in a comment, there is no notification about it as there was before
> 
> Did you check if the mention notifications are present after disabling the extension? If you have a mobile device, make sure you're getting notifications for the mentions on your app. If that's not the case, have a look at [notification settings on facebook](https://www.facebook.com/settings?tab=notifications) to see whether the notifications are enabled for mentions.
> 
> Alternatively you can also bookmark the [direct link to all notifications](https://www.facebook.com/notifications), if the notification pop-up window is bugged somehow, you should find all your notifications there.

Oki, seems like you were right :D The notification settings somehow changed, and I had to manually put back to get notification about mentions from EVERYONE... the default was from friends of friends... :)
